# Generated by Django 5.0 on 2023-12-20 13:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("spa", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="file",
            field=models.ImageField(
                blank=True, null=True, upload_to="images", verbose_name="file"
            ),
        ),
    ]
